language: node_js

node_js:
  - "4.0"

addons:
  postgresql: "9.4"

env:
  - DIALECT=mysql
  - DIALECT=postgres
  - DIALECT=postgres-native
  - DIALECT=sqlite
  - DIALECT=mariadb
  - DIALECT=mssql

before_script:
  - psql -c 'create database graphql_sequelize_test;' -U postgres

script:
  - "npm run check"

notifications:
  email: false
